### ISSUE TITLE
Possible to skip shell step?

### ISSUE THREAD

**Issue by rhysperry111** [Cacodemon345/uefidoom#1]
Would it be possible to stop using a UEFI shell and just boot directly into the doom.efi file? This would be cool to have as you could then add and EFI entry to boot straight into DOOM.

Thank you for you contributions to the DOOM community!

**Comment by Cacodemon345** [comment]
It isn't really possible due to the actual entry point requiring a Shell/C main function as of now.

However, you can try out the oldest release available here and see if it works.
