### ISSUE TITLE
Is it possible to add GRUB Bootloader entry for Playing DOOM? (+Any other command lines to Play other WAD Files besides DOOM 1?)

### ISSUE THREAD

**Issue by cyliamargatroid** [Cacodemon345/uefidoom#2]
Please tell me if GRUB2 Bootloader entry has Support to Play DOOM Game.

**Comment by Cacodemon345** [comment]
It's a UEFI shell-based application, meant to be ran from a UEFI shell.

Maybe it would be possible if GRUB2 was able to emulate a UEFI shell-based environment, but I don't believe it even supports that.

**Comment by anoraktrend** [comment]
Is it possible to do it in rEFInd, I wonder… it very well might. Are main releases 64bit?

**Comment by Cacodemon345** [comment]
I haven't really checked rEFInd. You may have to ask the author itself.
